# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /home/rgutierrez/cmake-2.8.1-Linux-i386/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rgutierrez/Programas/opencv-ossim-plugin

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rgutierrez/Programas/opencv-ossim-plugin

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/rgutierrez/cmake-2.8.1-Linux-i386/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rgutierrez/Programas/opencv-ossim-plugin/CMakeFiles /home/rgutierrez/Programas/opencv-ossim-plugin/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rgutierrez/Programas/opencv-ossim-plugin/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ossim

# Build rule for target.
ossim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ossim
.PHONY : ossim

# fast build rule for target.
ossim/fast:
	$(MAKE) -f CMakeFiles/ossim.dir/build.make CMakeFiles/ossim.dir/build
.PHONY : ossim/fast

#=============================================================================
# Target rules for targets named ossimopencv

# Build rule for target.
ossimopencv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ossimopencv
.PHONY : ossimopencv

# fast build rule for target.
ossimopencv/fast:
	$(MAKE) -f CMakeFiles/ossimopencv.dir/build.make CMakeFiles/ossimopencv.dir/build
.PHONY : ossimopencv/fast

#=============================================================================
# Target rules for targets named test_canny

# Build rule for target.
test_canny: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_canny
.PHONY : test_canny

# fast build rule for target.
test_canny/fast:
	$(MAKE) -f CMakeFiles/test_canny.dir/build.make CMakeFiles/test_canny.dir/build
.PHONY : test_canny/fast

#=============================================================================
# Target rules for targets named test_corners

# Build rule for target.
test_corners: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_corners
.PHONY : test_corners

# fast build rule for target.
test_corners/fast:
	$(MAKE) -f CMakeFiles/test_corners.dir/build.make CMakeFiles/test_corners.dir/build
.PHONY : test_corners/fast

#=============================================================================
# Target rules for targets named test_dilate

# Build rule for target.
test_dilate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_dilate
.PHONY : test_dilate

# fast build rule for target.
test_dilate/fast:
	$(MAKE) -f CMakeFiles/test_dilate.dir/build.make CMakeFiles/test_dilate.dir/build
.PHONY : test_dilate/fast

#=============================================================================
# Target rules for targets named test_erode

# Build rule for target.
test_erode: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_erode
.PHONY : test_erode

# fast build rule for target.
test_erode/fast:
	$(MAKE) -f CMakeFiles/test_erode.dir/build.make CMakeFiles/test_erode.dir/build
.PHONY : test_erode/fast

#=============================================================================
# Target rules for targets named test_laplace

# Build rule for target.
test_laplace: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_laplace
.PHONY : test_laplace

# fast build rule for target.
test_laplace/fast:
	$(MAKE) -f CMakeFiles/test_laplace.dir/build.make CMakeFiles/test_laplace.dir/build
.PHONY : test_laplace/fast

#=============================================================================
# Target rules for targets named test_pyrsegmentation

# Build rule for target.
test_pyrsegmentation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_pyrsegmentation
.PHONY : test_pyrsegmentation

# fast build rule for target.
test_pyrsegmentation/fast:
	$(MAKE) -f CMakeFiles/test_pyrsegmentation.dir/build.make CMakeFiles/test_pyrsegmentation.dir/build
.PHONY : test_pyrsegmentation/fast

#=============================================================================
# Target rules for targets named test_smooth

# Build rule for target.
test_smooth: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_smooth
.PHONY : test_smooth

# fast build rule for target.
test_smooth/fast:
	$(MAKE) -f CMakeFiles/test_smooth.dir/build.make CMakeFiles/test_smooth.dir/build
.PHONY : test_smooth/fast

#=============================================================================
# Target rules for targets named test_sobel

# Build rule for target.
test_sobel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_sobel
.PHONY : test_sobel

# fast build rule for target.
test_sobel/fast:
	$(MAKE) -f CMakeFiles/test_sobel.dir/build.make CMakeFiles/test_sobel.dir/build
.PHONY : test_sobel/fast

#=============================================================================
# Target rules for targets named test_threshold

# Build rule for target.
test_threshold: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_threshold
.PHONY : test_threshold

# fast build rule for target.
test_threshold/fast:
	$(MAKE) -f CMakeFiles/test_threshold.dir/build.make CMakeFiles/test_threshold.dir/build
.PHONY : test_threshold/fast

apps/canny.o: apps/canny.cpp.o
.PHONY : apps/canny.o

# target to build an object file
apps/canny.cpp.o:
	$(MAKE) -f CMakeFiles/test_canny.dir/build.make CMakeFiles/test_canny.dir/apps/canny.cpp.o
.PHONY : apps/canny.cpp.o

apps/canny.i: apps/canny.cpp.i
.PHONY : apps/canny.i

# target to preprocess a source file
apps/canny.cpp.i:
	$(MAKE) -f CMakeFiles/test_canny.dir/build.make CMakeFiles/test_canny.dir/apps/canny.cpp.i
.PHONY : apps/canny.cpp.i

apps/canny.s: apps/canny.cpp.s
.PHONY : apps/canny.s

# target to generate assembly for a file
apps/canny.cpp.s:
	$(MAKE) -f CMakeFiles/test_canny.dir/build.make CMakeFiles/test_canny.dir/apps/canny.cpp.s
.PHONY : apps/canny.cpp.s

apps/corners.o: apps/corners.cpp.o
.PHONY : apps/corners.o

# target to build an object file
apps/corners.cpp.o:
	$(MAKE) -f CMakeFiles/test_corners.dir/build.make CMakeFiles/test_corners.dir/apps/corners.cpp.o
.PHONY : apps/corners.cpp.o

apps/corners.i: apps/corners.cpp.i
.PHONY : apps/corners.i

# target to preprocess a source file
apps/corners.cpp.i:
	$(MAKE) -f CMakeFiles/test_corners.dir/build.make CMakeFiles/test_corners.dir/apps/corners.cpp.i
.PHONY : apps/corners.cpp.i

apps/corners.s: apps/corners.cpp.s
.PHONY : apps/corners.s

# target to generate assembly for a file
apps/corners.cpp.s:
	$(MAKE) -f CMakeFiles/test_corners.dir/build.make CMakeFiles/test_corners.dir/apps/corners.cpp.s
.PHONY : apps/corners.cpp.s

apps/dilate.o: apps/dilate.cpp.o
.PHONY : apps/dilate.o

# target to build an object file
apps/dilate.cpp.o:
	$(MAKE) -f CMakeFiles/test_dilate.dir/build.make CMakeFiles/test_dilate.dir/apps/dilate.cpp.o
.PHONY : apps/dilate.cpp.o

apps/dilate.i: apps/dilate.cpp.i
.PHONY : apps/dilate.i

# target to preprocess a source file
apps/dilate.cpp.i:
	$(MAKE) -f CMakeFiles/test_dilate.dir/build.make CMakeFiles/test_dilate.dir/apps/dilate.cpp.i
.PHONY : apps/dilate.cpp.i

apps/dilate.s: apps/dilate.cpp.s
.PHONY : apps/dilate.s

# target to generate assembly for a file
apps/dilate.cpp.s:
	$(MAKE) -f CMakeFiles/test_dilate.dir/build.make CMakeFiles/test_dilate.dir/apps/dilate.cpp.s
.PHONY : apps/dilate.cpp.s

apps/erode.o: apps/erode.cpp.o
.PHONY : apps/erode.o

# target to build an object file
apps/erode.cpp.o:
	$(MAKE) -f CMakeFiles/test_erode.dir/build.make CMakeFiles/test_erode.dir/apps/erode.cpp.o
.PHONY : apps/erode.cpp.o

apps/erode.i: apps/erode.cpp.i
.PHONY : apps/erode.i

# target to preprocess a source file
apps/erode.cpp.i:
	$(MAKE) -f CMakeFiles/test_erode.dir/build.make CMakeFiles/test_erode.dir/apps/erode.cpp.i
.PHONY : apps/erode.cpp.i

apps/erode.s: apps/erode.cpp.s
.PHONY : apps/erode.s

# target to generate assembly for a file
apps/erode.cpp.s:
	$(MAKE) -f CMakeFiles/test_erode.dir/build.make CMakeFiles/test_erode.dir/apps/erode.cpp.s
.PHONY : apps/erode.cpp.s

apps/laplace.o: apps/laplace.cpp.o
.PHONY : apps/laplace.o

# target to build an object file
apps/laplace.cpp.o:
	$(MAKE) -f CMakeFiles/test_laplace.dir/build.make CMakeFiles/test_laplace.dir/apps/laplace.cpp.o
.PHONY : apps/laplace.cpp.o

apps/laplace.i: apps/laplace.cpp.i
.PHONY : apps/laplace.i

# target to preprocess a source file
apps/laplace.cpp.i:
	$(MAKE) -f CMakeFiles/test_laplace.dir/build.make CMakeFiles/test_laplace.dir/apps/laplace.cpp.i
.PHONY : apps/laplace.cpp.i

apps/laplace.s: apps/laplace.cpp.s
.PHONY : apps/laplace.s

# target to generate assembly for a file
apps/laplace.cpp.s:
	$(MAKE) -f CMakeFiles/test_laplace.dir/build.make CMakeFiles/test_laplace.dir/apps/laplace.cpp.s
.PHONY : apps/laplace.cpp.s

apps/pyrsegmentation.o: apps/pyrsegmentation.cpp.o
.PHONY : apps/pyrsegmentation.o

# target to build an object file
apps/pyrsegmentation.cpp.o:
	$(MAKE) -f CMakeFiles/test_pyrsegmentation.dir/build.make CMakeFiles/test_pyrsegmentation.dir/apps/pyrsegmentation.cpp.o
.PHONY : apps/pyrsegmentation.cpp.o

apps/pyrsegmentation.i: apps/pyrsegmentation.cpp.i
.PHONY : apps/pyrsegmentation.i

# target to preprocess a source file
apps/pyrsegmentation.cpp.i:
	$(MAKE) -f CMakeFiles/test_pyrsegmentation.dir/build.make CMakeFiles/test_pyrsegmentation.dir/apps/pyrsegmentation.cpp.i
.PHONY : apps/pyrsegmentation.cpp.i

apps/pyrsegmentation.s: apps/pyrsegmentation.cpp.s
.PHONY : apps/pyrsegmentation.s

# target to generate assembly for a file
apps/pyrsegmentation.cpp.s:
	$(MAKE) -f CMakeFiles/test_pyrsegmentation.dir/build.make CMakeFiles/test_pyrsegmentation.dir/apps/pyrsegmentation.cpp.s
.PHONY : apps/pyrsegmentation.cpp.s

apps/smooth.o: apps/smooth.cpp.o
.PHONY : apps/smooth.o

# target to build an object file
apps/smooth.cpp.o:
	$(MAKE) -f CMakeFiles/test_smooth.dir/build.make CMakeFiles/test_smooth.dir/apps/smooth.cpp.o
.PHONY : apps/smooth.cpp.o

apps/smooth.i: apps/smooth.cpp.i
.PHONY : apps/smooth.i

# target to preprocess a source file
apps/smooth.cpp.i:
	$(MAKE) -f CMakeFiles/test_smooth.dir/build.make CMakeFiles/test_smooth.dir/apps/smooth.cpp.i
.PHONY : apps/smooth.cpp.i

apps/smooth.s: apps/smooth.cpp.s
.PHONY : apps/smooth.s

# target to generate assembly for a file
apps/smooth.cpp.s:
	$(MAKE) -f CMakeFiles/test_smooth.dir/build.make CMakeFiles/test_smooth.dir/apps/smooth.cpp.s
.PHONY : apps/smooth.cpp.s

apps/sobel.o: apps/sobel.cpp.o
.PHONY : apps/sobel.o

# target to build an object file
apps/sobel.cpp.o:
	$(MAKE) -f CMakeFiles/test_sobel.dir/build.make CMakeFiles/test_sobel.dir/apps/sobel.cpp.o
.PHONY : apps/sobel.cpp.o

apps/sobel.i: apps/sobel.cpp.i
.PHONY : apps/sobel.i

# target to preprocess a source file
apps/sobel.cpp.i:
	$(MAKE) -f CMakeFiles/test_sobel.dir/build.make CMakeFiles/test_sobel.dir/apps/sobel.cpp.i
.PHONY : apps/sobel.cpp.i

apps/sobel.s: apps/sobel.cpp.s
.PHONY : apps/sobel.s

# target to generate assembly for a file
apps/sobel.cpp.s:
	$(MAKE) -f CMakeFiles/test_sobel.dir/build.make CMakeFiles/test_sobel.dir/apps/sobel.cpp.s
.PHONY : apps/sobel.cpp.s

apps/threshold.o: apps/threshold.cpp.o
.PHONY : apps/threshold.o

# target to build an object file
apps/threshold.cpp.o:
	$(MAKE) -f CMakeFiles/test_threshold.dir/build.make CMakeFiles/test_threshold.dir/apps/threshold.cpp.o
.PHONY : apps/threshold.cpp.o

apps/threshold.i: apps/threshold.cpp.i
.PHONY : apps/threshold.i

# target to preprocess a source file
apps/threshold.cpp.i:
	$(MAKE) -f CMakeFiles/test_threshold.dir/build.make CMakeFiles/test_threshold.dir/apps/threshold.cpp.i
.PHONY : apps/threshold.cpp.i

apps/threshold.s: apps/threshold.cpp.s
.PHONY : apps/threshold.s

# target to generate assembly for a file
apps/threshold.cpp.s:
	$(MAKE) -f CMakeFiles/test_threshold.dir/build.make CMakeFiles/test_threshold.dir/apps/threshold.cpp.s
.PHONY : apps/threshold.cpp.s

ossimOpenCVCannyFilter.o: ossimOpenCVCannyFilter.cpp.o
.PHONY : ossimOpenCVCannyFilter.o

# target to build an object file
ossimOpenCVCannyFilter.cpp.o:
	$(MAKE) -f CMakeFiles/ossimopencv.dir/build.make CMakeFiles/ossimopencv.dir/ossimOpenCVCannyFilter.cpp.o
.PHONY : ossimOpenCVCannyFilter.cpp.o

ossimOpenCVCannyFilter.i: ossimOpenCVCannyFilter.cpp.i
.PHONY : ossimOpenCVCannyFilter.i

# target to preprocess a source file
ossimOpenCVCannyFilter.cpp.i:
	$(MAKE) -f CMakeFiles/ossimopencv.dir/build.make CMakeFiles/ossimopencv.dir/ossimOpenCVCannyFilter.cpp.i
.PHONY : ossimOpenCVCannyFilter.cpp.i

ossimOpenCVCannyFilter.s: ossimOpenCVCannyFilter.cpp.s
.PHONY : ossimOpenCVCannyFilter.s

# target to generate assembly for a file
ossimOpenCVCannyFilter.cpp.s:
	$(MAKE) -f CMakeFiles/ossimopencv.dir/build.make CMakeFiles/ossimopencv.dir/ossimOpenCVCannyFilter.cpp.s
.PHONY : ossimOpenCVCannyFilter.cpp.s

ossimOpenCVDilateFilter.o: ossimOpenCVDilateFilter.cpp.o
.PHONY : ossimOpenCVDilateFilter.o

# target to build an object file
ossimOpenCVDilateFilter.cpp.o:
	$(MAKE) -f CMakeFiles/ossimopencv.dir/build.make CMakeFiles/ossimopencv.dir/ossimOpenCVDilateFilter.cpp.o
.PHONY : ossimOpenCVDilateFilter.cpp.o

ossimOpenCVDilateFilter.i: ossimOpenCVDilateFilter.cpp.i
.PHONY : ossimOpenCVDilateFilter.i

# target to preprocess a source file
ossimOpenCVDilateFilter.cpp.i:
	$(MAKE) -f CMakeFiles/ossimopencv.dir/build.make CMakeFiles/ossimopencv.dir/ossimOpenCVDilateFilter.cpp.i
.PHONY : ossimOpenCVDilateFilter.cpp.i

ossimOpenCVDilateFilter.s: ossimOpenCVDilateFilter.cpp.s
.PHONY : ossimOpenCVDilateFilter.s

# target to generate assembly for a file
ossimOpenCVDilateFilter.cpp.s:
	$(MAKE) -f CMakeFiles/ossimopencv.dir/build.make CMakeFiles/ossimopencv.dir/ossimOpenCVDilateFilter.cpp.s
.PHONY : ossimOpenCVDilateFilter.cpp.s

ossimOpenCVErodeFilter.o: ossimOpenCVErodeFilter.cpp.o
.PHONY : ossimOpenCVErodeFilter.o

# target to build an object file
ossimOpenCVErodeFilter.cpp.o:
	$(MAKE) -f CMakeFiles/ossimopencv.dir/build.make CMakeFiles/ossimopencv.dir/ossimOpenCVErodeFilter.cpp.o
.PHONY : ossimOpenCVErodeFilter.cpp.o

ossimOpenCVErodeFilter.i: ossimOpenCVErodeFilter.cpp.i
.PHONY : ossimOpenCVErodeFilter.i

# target to preprocess a source file
ossimOpenCVErodeFilter.cpp.i:
	$(MAKE) -f CMakeFiles/ossimopencv.dir/build.make CMakeFiles/ossimopencv.dir/ossimOpenCVErodeFilter.cpp.i
.PHONY : ossimOpenCVErodeFilter.cpp.i

ossimOpenCVErodeFilter.s: ossimOpenCVErodeFilter.cpp.s
.PHONY : ossimOpenCVErodeFilter.s

# target to generate assembly for a file
ossimOpenCVErodeFilter.cpp.s:
	$(MAKE) -f CMakeFiles/ossimopencv.dir/build.make CMakeFiles/ossimopencv.dir/ossimOpenCVErodeFilter.cpp.s
.PHONY : ossimOpenCVErodeFilter.cpp.s

ossimOpenCVGoodFeaturesToTrack.o: ossimOpenCVGoodFeaturesToTrack.cpp.o
.PHONY : ossimOpenCVGoodFeaturesToTrack.o

# target to build an object file
ossimOpenCVGoodFeaturesToTrack.cpp.o:
	$(MAKE) -f CMakeFiles/ossimopencv.dir/build.make CMakeFiles/ossimopencv.dir/ossimOpenCVGoodFeaturesToTrack.cpp.o
.PHONY : ossimOpenCVGoodFeaturesToTrack.cpp.o

ossimOpenCVGoodFeaturesToTrack.i: ossimOpenCVGoodFeaturesToTrack.cpp.i
.PHONY : ossimOpenCVGoodFeaturesToTrack.i

# target to preprocess a source file
ossimOpenCVGoodFeaturesToTrack.cpp.i:
	$(MAKE) -f CMakeFiles/ossimopencv.dir/build.make CMakeFiles/ossimopencv.dir/ossimOpenCVGoodFeaturesToTrack.cpp.i
.PHONY : ossimOpenCVGoodFeaturesToTrack.cpp.i

ossimOpenCVGoodFeaturesToTrack.s: ossimOpenCVGoodFeaturesToTrack.cpp.s
.PHONY : ossimOpenCVGoodFeaturesToTrack.s

# target to generate assembly for a file
ossimOpenCVGoodFeaturesToTrack.cpp.s:
	$(MAKE) -f CMakeFiles/ossimopencv.dir/build.make CMakeFiles/ossimopencv.dir/ossimOpenCVGoodFeaturesToTrack.cpp.s
.PHONY : ossimOpenCVGoodFeaturesToTrack.cpp.s

ossimOpenCVLaplaceFilter.o: ossimOpenCVLaplaceFilter.cpp.o
.PHONY : ossimOpenCVLaplaceFilter.o

# target to build an object file
ossimOpenCVLaplaceFilter.cpp.o:
	$(MAKE) -f CMakeFiles/ossimopencv.dir/build.make CMakeFiles/ossimopencv.dir/ossimOpenCVLaplaceFilter.cpp.o
.PHONY : ossimOpenCVLaplaceFilter.cpp.o

ossimOpenCVLaplaceFilter.i: ossimOpenCVLaplaceFilter.cpp.i
.PHONY : ossimOpenCVLaplaceFilter.i

# target to preprocess a source file
ossimOpenCVLaplaceFilter.cpp.i:
	$(MAKE) -f CMakeFiles/ossimopencv.dir/build.make CMakeFiles/ossimopencv.dir/ossimOpenCVLaplaceFilter.cpp.i
.PHONY : ossimOpenCVLaplaceFilter.cpp.i

ossimOpenCVLaplaceFilter.s: ossimOpenCVLaplaceFilter.cpp.s
.PHONY : ossimOpenCVLaplaceFilter.s

# target to generate assembly for a file
ossimOpenCVLaplaceFilter.cpp.s:
	$(MAKE) -f CMakeFiles/ossimopencv.dir/build.make CMakeFiles/ossimopencv.dir/ossimOpenCVLaplaceFilter.cpp.s
.PHONY : ossimOpenCVLaplaceFilter.cpp.s

ossimOpenCVPluginFactory.o: ossimOpenCVPluginFactory.cpp.o
.PHONY : ossimOpenCVPluginFactory.o

# target to build an object file
ossimOpenCVPluginFactory.cpp.o:
	$(MAKE) -f CMakeFiles/ossimopencv.dir/build.make CMakeFiles/ossimopencv.dir/ossimOpenCVPluginFactory.cpp.o
.PHONY : ossimOpenCVPluginFactory.cpp.o

ossimOpenCVPluginFactory.i: ossimOpenCVPluginFactory.cpp.i
.PHONY : ossimOpenCVPluginFactory.i

# target to preprocess a source file
ossimOpenCVPluginFactory.cpp.i:
	$(MAKE) -f CMakeFiles/ossimopencv.dir/build.make CMakeFiles/ossimopencv.dir/ossimOpenCVPluginFactory.cpp.i
.PHONY : ossimOpenCVPluginFactory.cpp.i

ossimOpenCVPluginFactory.s: ossimOpenCVPluginFactory.cpp.s
.PHONY : ossimOpenCVPluginFactory.s

# target to generate assembly for a file
ossimOpenCVPluginFactory.cpp.s:
	$(MAKE) -f CMakeFiles/ossimopencv.dir/build.make CMakeFiles/ossimopencv.dir/ossimOpenCVPluginFactory.cpp.s
.PHONY : ossimOpenCVPluginFactory.cpp.s

ossimOpenCVPluginInit.o: ossimOpenCVPluginInit.cpp.o
.PHONY : ossimOpenCVPluginInit.o

# target to build an object file
ossimOpenCVPluginInit.cpp.o:
	$(MAKE) -f CMakeFiles/ossimopencv.dir/build.make CMakeFiles/ossimopencv.dir/ossimOpenCVPluginInit.cpp.o
.PHONY : ossimOpenCVPluginInit.cpp.o

ossimOpenCVPluginInit.i: ossimOpenCVPluginInit.cpp.i
.PHONY : ossimOpenCVPluginInit.i

# target to preprocess a source file
ossimOpenCVPluginInit.cpp.i:
	$(MAKE) -f CMakeFiles/ossimopencv.dir/build.make CMakeFiles/ossimopencv.dir/ossimOpenCVPluginInit.cpp.i
.PHONY : ossimOpenCVPluginInit.cpp.i

ossimOpenCVPluginInit.s: ossimOpenCVPluginInit.cpp.s
.PHONY : ossimOpenCVPluginInit.s

# target to generate assembly for a file
ossimOpenCVPluginInit.cpp.s:
	$(MAKE) -f CMakeFiles/ossimopencv.dir/build.make CMakeFiles/ossimopencv.dir/ossimOpenCVPluginInit.cpp.s
.PHONY : ossimOpenCVPluginInit.cpp.s

ossimOpenCVPyrSegmentation.o: ossimOpenCVPyrSegmentation.cpp.o
.PHONY : ossimOpenCVPyrSegmentation.o

# target to build an object file
ossimOpenCVPyrSegmentation.cpp.o:
	$(MAKE) -f CMakeFiles/ossimopencv.dir/build.make CMakeFiles/ossimopencv.dir/ossimOpenCVPyrSegmentation.cpp.o
.PHONY : ossimOpenCVPyrSegmentation.cpp.o

ossimOpenCVPyrSegmentation.i: ossimOpenCVPyrSegmentation.cpp.i
.PHONY : ossimOpenCVPyrSegmentation.i

# target to preprocess a source file
ossimOpenCVPyrSegmentation.cpp.i:
	$(MAKE) -f CMakeFiles/ossimopencv.dir/build.make CMakeFiles/ossimopencv.dir/ossimOpenCVPyrSegmentation.cpp.i
.PHONY : ossimOpenCVPyrSegmentation.cpp.i

ossimOpenCVPyrSegmentation.s: ossimOpenCVPyrSegmentation.cpp.s
.PHONY : ossimOpenCVPyrSegmentation.s

# target to generate assembly for a file
ossimOpenCVPyrSegmentation.cpp.s:
	$(MAKE) -f CMakeFiles/ossimopencv.dir/build.make CMakeFiles/ossimopencv.dir/ossimOpenCVPyrSegmentation.cpp.s
.PHONY : ossimOpenCVPyrSegmentation.cpp.s

ossimOpenCVSmoothFilter.o: ossimOpenCVSmoothFilter.cpp.o
.PHONY : ossimOpenCVSmoothFilter.o

# target to build an object file
ossimOpenCVSmoothFilter.cpp.o:
	$(MAKE) -f CMakeFiles/ossimopencv.dir/build.make CMakeFiles/ossimopencv.dir/ossimOpenCVSmoothFilter.cpp.o
.PHONY : ossimOpenCVSmoothFilter.cpp.o

ossimOpenCVSmoothFilter.i: ossimOpenCVSmoothFilter.cpp.i
.PHONY : ossimOpenCVSmoothFilter.i

# target to preprocess a source file
ossimOpenCVSmoothFilter.cpp.i:
	$(MAKE) -f CMakeFiles/ossimopencv.dir/build.make CMakeFiles/ossimopencv.dir/ossimOpenCVSmoothFilter.cpp.i
.PHONY : ossimOpenCVSmoothFilter.cpp.i

ossimOpenCVSmoothFilter.s: ossimOpenCVSmoothFilter.cpp.s
.PHONY : ossimOpenCVSmoothFilter.s

# target to generate assembly for a file
ossimOpenCVSmoothFilter.cpp.s:
	$(MAKE) -f CMakeFiles/ossimopencv.dir/build.make CMakeFiles/ossimopencv.dir/ossimOpenCVSmoothFilter.cpp.s
.PHONY : ossimOpenCVSmoothFilter.cpp.s

ossimOpenCVSobelFilter.o: ossimOpenCVSobelFilter.cpp.o
.PHONY : ossimOpenCVSobelFilter.o

# target to build an object file
ossimOpenCVSobelFilter.cpp.o:
	$(MAKE) -f CMakeFiles/ossimopencv.dir/build.make CMakeFiles/ossimopencv.dir/ossimOpenCVSobelFilter.cpp.o
.PHONY : ossimOpenCVSobelFilter.cpp.o

ossimOpenCVSobelFilter.i: ossimOpenCVSobelFilter.cpp.i
.PHONY : ossimOpenCVSobelFilter.i

# target to preprocess a source file
ossimOpenCVSobelFilter.cpp.i:
	$(MAKE) -f CMakeFiles/ossimopencv.dir/build.make CMakeFiles/ossimopencv.dir/ossimOpenCVSobelFilter.cpp.i
.PHONY : ossimOpenCVSobelFilter.cpp.i

ossimOpenCVSobelFilter.s: ossimOpenCVSobelFilter.cpp.s
.PHONY : ossimOpenCVSobelFilter.s

# target to generate assembly for a file
ossimOpenCVSobelFilter.cpp.s:
	$(MAKE) -f CMakeFiles/ossimopencv.dir/build.make CMakeFiles/ossimopencv.dir/ossimOpenCVSobelFilter.cpp.s
.PHONY : ossimOpenCVSobelFilter.cpp.s

ossimOpenCVThresholdFilter.o: ossimOpenCVThresholdFilter.cpp.o
.PHONY : ossimOpenCVThresholdFilter.o

# target to build an object file
ossimOpenCVThresholdFilter.cpp.o:
	$(MAKE) -f CMakeFiles/ossimopencv.dir/build.make CMakeFiles/ossimopencv.dir/ossimOpenCVThresholdFilter.cpp.o
.PHONY : ossimOpenCVThresholdFilter.cpp.o

ossimOpenCVThresholdFilter.i: ossimOpenCVThresholdFilter.cpp.i
.PHONY : ossimOpenCVThresholdFilter.i

# target to preprocess a source file
ossimOpenCVThresholdFilter.cpp.i:
	$(MAKE) -f CMakeFiles/ossimopencv.dir/build.make CMakeFiles/ossimopencv.dir/ossimOpenCVThresholdFilter.cpp.i
.PHONY : ossimOpenCVThresholdFilter.cpp.i

ossimOpenCVThresholdFilter.s: ossimOpenCVThresholdFilter.cpp.s
.PHONY : ossimOpenCVThresholdFilter.s

# target to generate assembly for a file
ossimOpenCVThresholdFilter.cpp.s:
	$(MAKE) -f CMakeFiles/ossimopencv.dir/build.make CMakeFiles/ossimopencv.dir/ossimOpenCVThresholdFilter.cpp.s
.PHONY : ossimOpenCVThresholdFilter.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... ossim"
	@echo "... ossimopencv"
	@echo "... rebuild_cache"
	@echo "... test_canny"
	@echo "... test_corners"
	@echo "... test_dilate"
	@echo "... test_erode"
	@echo "... test_laplace"
	@echo "... test_pyrsegmentation"
	@echo "... test_smooth"
	@echo "... test_sobel"
	@echo "... test_threshold"
	@echo "... apps/canny.o"
	@echo "... apps/canny.i"
	@echo "... apps/canny.s"
	@echo "... apps/corners.o"
	@echo "... apps/corners.i"
	@echo "... apps/corners.s"
	@echo "... apps/dilate.o"
	@echo "... apps/dilate.i"
	@echo "... apps/dilate.s"
	@echo "... apps/erode.o"
	@echo "... apps/erode.i"
	@echo "... apps/erode.s"
	@echo "... apps/laplace.o"
	@echo "... apps/laplace.i"
	@echo "... apps/laplace.s"
	@echo "... apps/pyrsegmentation.o"
	@echo "... apps/pyrsegmentation.i"
	@echo "... apps/pyrsegmentation.s"
	@echo "... apps/smooth.o"
	@echo "... apps/smooth.i"
	@echo "... apps/smooth.s"
	@echo "... apps/sobel.o"
	@echo "... apps/sobel.i"
	@echo "... apps/sobel.s"
	@echo "... apps/threshold.o"
	@echo "... apps/threshold.i"
	@echo "... apps/threshold.s"
	@echo "... ossimOpenCVCannyFilter.o"
	@echo "... ossimOpenCVCannyFilter.i"
	@echo "... ossimOpenCVCannyFilter.s"
	@echo "... ossimOpenCVDilateFilter.o"
	@echo "... ossimOpenCVDilateFilter.i"
	@echo "... ossimOpenCVDilateFilter.s"
	@echo "... ossimOpenCVErodeFilter.o"
	@echo "... ossimOpenCVErodeFilter.i"
	@echo "... ossimOpenCVErodeFilter.s"
	@echo "... ossimOpenCVGoodFeaturesToTrack.o"
	@echo "... ossimOpenCVGoodFeaturesToTrack.i"
	@echo "... ossimOpenCVGoodFeaturesToTrack.s"
	@echo "... ossimOpenCVLaplaceFilter.o"
	@echo "... ossimOpenCVLaplaceFilter.i"
	@echo "... ossimOpenCVLaplaceFilter.s"
	@echo "... ossimOpenCVPluginFactory.o"
	@echo "... ossimOpenCVPluginFactory.i"
	@echo "... ossimOpenCVPluginFactory.s"
	@echo "... ossimOpenCVPluginInit.o"
	@echo "... ossimOpenCVPluginInit.i"
	@echo "... ossimOpenCVPluginInit.s"
	@echo "... ossimOpenCVPyrSegmentation.o"
	@echo "... ossimOpenCVPyrSegmentation.i"
	@echo "... ossimOpenCVPyrSegmentation.s"
	@echo "... ossimOpenCVSmoothFilter.o"
	@echo "... ossimOpenCVSmoothFilter.i"
	@echo "... ossimOpenCVSmoothFilter.s"
	@echo "... ossimOpenCVSobelFilter.o"
	@echo "... ossimOpenCVSobelFilter.i"
	@echo "... ossimOpenCVSobelFilter.s"
	@echo "... ossimOpenCVThresholdFilter.o"
	@echo "... ossimOpenCVThresholdFilter.i"
	@echo "... ossimOpenCVThresholdFilter.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

